#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
    CREATE DATABASE prod_db;
    CREATE DATABASE dev_db;
    CREATE DATABASE test_db;
    GRANT ALL PRIVILEGES ON DATABASE prod_db TO "$POSTGRES_USER";
    GRANT ALL PRIVILEGES ON DATABASE dev_db TO "$POSTGRES_USER";
    GRANT ALL PRIVILEGES ON DATABASE test_db TO "$POSTGRES_USER";
EOSQL
